global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "payment-api"
    static_configs:
      - targets: ["host.docker.internal:5400"]

  - job_name: "product-api"
    static_configs:
      - targets: ["host.docker.internal:5200"]

  - job_name: "user-api"
    static_configs:
      - targets: ["host.docker.internal:5300"]

  - job_name: "graphql-gateway"
    static_configs:
      - targets: ["host.docker.internal:5443"]

  - job_name: "webhooks"
    static_configs:
      - targets: ["host.docker.internal:7071"]

  - job_name: "plans-listener"
    static_configs:
      - targets: ["plans-listener:7100"]

  - job_name: "plan-subscription-listener"
    static_configs:
      - targets: ["plan-subscription-listener:7100"]

  - job_name: "payments-listener"
    static_configs:
      - targets: ["payments-listener:7100"]

  - job_name: "notifications-listener"
    static_configs:
      - targets: ["notifications-listener:7100"]

  - job_name: "price-tiers-listener"
    static_configs:
      - targets: ["price-tiers-listener:7100"]

  - job_name: "clients-listener"
    static_configs:
      - targets: ["clients-listener:7100"]

  - job_name: "auth-api"
    static_configs:
      - targets: ["host.docker.internal:5555"]

  # - job_name: "localizer-api"
  #   static_configs: # TODO: need an endpoint to scrape
  #     - targets: ["host.docker.internal:8888"]
