site_name: Nudges System Documentation
site_url: https://docs.nudges.dev/
remote_branch: docs

nav:
  - "Introduction": "index.md"
  - "Getting Started": "getting-started.md"
  - "Scripts": "scripts.md"
  - "Docker": "docker.md"
  - "infrastructure.md"
  - Integrations:
    - "Stripe": "integrations/stripe.md"
    - "Twilio": "integrations/twilio.md"
  - Services:
    - "AuthApi": "services/auth-api.md"
    - "AuthInit": "services/auth-init.md"
    - "Database Migrator": "services/db-migrator.md"
    - "Database Seeder": "services/db-seeder.md"
    - "GraphMonitor": "services/graph-monitor.md"
    - "GraphQL Gateway": "services/graphql-gateway.md"
    - "KafkaConsumer": "services/kafka-consumer.md"
    - "LocalizationApi": "services/localization-api.md"
    - "PaymentApi": "services/payment-api.md"
    - "ProductApi": "services/product-api.md"
    - "UserApi": "services/user-api.md"
    - "WarpCache": "services/warpcache.md"
    - "Webhooks": "services/webhooks.md"
  - Database:
    - "Overview": "data/index.md"
    - "Users": "data/userdb.md"
    - "Payments": "data/paymentdb.md"
    - "Products": "data/productdb.md"


extra_css: [css/docs.css]
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

plugins:
  - search
  - exclude:
      glob:
        - snippets/*

repo_url: https://github.com/getnudges/monov4
repo_name: getnudges/monov4

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: True



